//
// Created by denis on 01.04.17.
//

#ifndef GEO_NETWORK_CLIENT_CYCLESSIXNODESINITTRANSACTION_H
#define GEO_NETWORK_CLIENT_CYCLESSIXNODESINITTRANSACTION_H

#endif //GEO_NETWORK_CLIENT_CYCLESSIXNODESINITTRANSACTION_H
